config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  resources :songs
  devise_for :users

  # Static pages
  root to: 'static_pages#home'
  get 'privacy', to: 'static_pages#privacy_policy'
  post 'contact_mail', to: 'static_pages#contact_mail'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms_of_use'
  get 'copyright', to: 'static_pages#copyright_claims'
  get 'test', to: 'test#test'

  # Search
  get 'search', to: 'search#get'
  post 'search', to: 'search#post'

  # Playlist
  get 'user_songs', to: 'songs#user_index'
  get 'user_updated', to: 'songs#user_updated'
  get 'user_not_updated', to: 'songs#user_not_updated'
  get 'auto_fill', to: 'songs#auto_fill'
  post 'remove', to: 'playlist#remove'
  post 'add', to: 'playlist#add'
  get 'profile', to: 'profiles#show'

  # Albums
  get 'albums', to: 'albums#get'

  # Devices
  delete 'wipe_device', to: 'devices#wipe_device'
  delete 'delete_device', to: 'devices#destroy'
  post 'merge_devices', to: 'devices#merge'

  # Downloads
  get 'internal_download', to: 'download#internal'
  get 'external_download', to: 'download#external'
  get 'update_download', to: 'download#update'
  get 'download_all', to: 'download#all'
  get 'retry_download', to: 'download#retry'

  # Notifications
  get 'get_uuid', to: 'notifications#get_uuid'
  get 'mark_as_read', to: 'notifications#mark_as_read'
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def show; end
end

app/views/profiles/show.slim
.container
  .is-size-1 Profile
  .columns
    .column
      .is-size-3 Device Settings
      .help.is-info.pb-3 
        | This helps with the download all only downloading outstanding songs
      .is-size-5 Known Devices
      - current_user.devices.each do |device|
        .card.m-3.p-3
          .control
            = device.user_agent
          .field.is-grouped
            .control
              = button_to "Wipe Device", wipe_device_path(id: device.id), method: :delete, class: "button is-warning"
            .control
              = button_to "Delete Device", delete_device_path(id: device.id), method: :delete, class: "button is-danger"
      .is-size-5 Merge device libraries
      = form_with url: merge_devices_path do |f|
        .card.p-3.m-3
          .field
            .label Merge
            .control
              .select.is-fullwidth
                = f.select :parent, current_user.devices.all.pluck(:user_agent)
          .field
            .label Into
            .control
              .select.is-fullwidth
                = f.select :child, current_user.devices.all.pluck(:user_agent)
            .help.is-info
              | Merges all the songs in the child device into 
              | the parent if you have moved music manually
            .control.mt-2
              = f.submit "Merge Devices", class: "button is-info"

    .column 
      .is-size-3 Settings