config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  resources :songs
  devise_for :users

  # Static pages
  root to: 'static_pages#home'
  get 'privacy', to: 'static_pages#privacy_policy'
  post 'contact_mail', to: 'static_pages#contact_mail'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms_of_use'
  get 'copyright', to: 'static_pages#copyright_claims'
  get 'test', to: 'test#test'

  # Search
  get 'search', to: 'search#get'
  post 'search', to: 'search#post'

  # Playlist
  get 'user_songs', to: 'songs#user_index'
  get 'user_updated', to: 'songs#user_updated'
  get 'user_not_updated', to: 'songs#user_not_updated'
  get 'auto_fill', to: 'songs#auto_fill'
  post 'remove', to: 'playlist#remove'
  post 'add', to: 'playlist#add'
  get 'profile', to: 'profiles#show'

  # Albums
  get 'albums', to: 'albums#get'

  # Devices
  delete 'wipe_device', to: 'devices#wipe_device'
  delete 'delete_device', to: 'devices#destroy'
  post 'merge_devices', to: 'devices#merge'

  # Downloads
  get 'internal_download', to: 'download#internal'
  get 'external_download', to: 'download#external'
  get 'update_download', to: 'download#update'
  get 'download_all', to: 'download#all'
  get 'retry_download', to: 'download#retry'

  # Notifications
  get 'get_uuid', to: 'notifications#get_uuid'
  get 'mark_as_read', to: 'notifications#mark_as_read'
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  has_one_attached :image
  has_one_attached :mp3
  has_many :user_songs, dependent: :destroy
  has_many :users, through: :user_songs
  has_many :device_songs, dependent: :destroy
  has_many :devices, through: :device_songs
  validates :title, presence: true
  validates :video_id, presence: true, uniqueness: true

  def redownload
    # redownload the file then attach the mp3 file
  end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  before_action :set_song, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[user_index show new edit create update delete]

  def index
    @q = Song.all.ransack(params[:q])
    @songs = @q.result.page(params[:page])
  end

  def user_index
    @q = current_user.songs.ransack(params[:q])
    @songs = @q.result.page(params[:page])
  end

  def user_updated
    @q = current_user.songs.where("updated >= 1").ransack(params[:q])
    @songs = @q.result.page(params[:page])
  end

  def user_not_updated
    @q = current_user.songs.where(updated: 0).ransack(params[:q])
    @songs = @q.result.page(params[:page])
  end

  def auto_fill
    response = ::Songs::UseCases::AutoFill.call(params)
    # Net::HTTP.get("https://musicbrainz.org/ws/2/artist?query=post+malone&limit=1&offset=0")
    render json: response.to_json
  end

  def show; end

  def new
    @song = Song.new
  end

  def edit; end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    parsed_params = song_params.to_h
    # parsed_params = params.dup.to_h
    parsed_params.merge!({ updated: 1 }).except!(:id, :authenticity_token, :commit)
    pp parsed_params
    if @song.update(parsed_params)
      redirect_back fallback_location: songs_path, notice: "Song was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def song_params
    params.require(:song).permit(:genre, :year, :title, :album, :artist)
  end
end

app/views/songs/_auto_fill.slim
javascript: 

  auto = document.getElementsByClassName("auto-fill")

  for( i = 0; i < auto.length; i++ ) {
    auto[i].addEventListener("click", (e) => {
      e.preventDefault
      id = e.target.dataset.id
      artist_el = artist_func(id)
      fetch(("#{ENV['API_URL']}/auto_fill?artist=" +
        encodeURIComponent(artist_func(id).value))).then(data => data.json())
        .then(data => artistDropdown(data, id))
    })
  }

  artist_func = function(id) {
    artist = find_item_by(id, "artist");
    return artist
  }

  album_func = function(id) {
    album = find_item_by(id, "album");
    return album
  }

  title_func = function(id) {
    title = find_item_by(id, "name")
    return title
  }

  year_func = function(id) {
    year = find_item_by(id, "year")
    return year
  }

  genre_func = function(id) {
    genre = find_item_by(id, "genre")
    return genre
  }


  form_func = function(id) {
    form = find_item_by(id, "forming")
    return form
  }

  function find_item_by(id, class_name) {
    items = document.getElementsByClassName(class_name);
    for ( i = 0; i < items.length; i++) {
      if (items[i].dataset.id == id) {
        return items[i]
      }
    }
  }

  function artistDropdown(data, id) {
    form = form_func(id)
    form.innerHTML = ""
    var selectList = "<div class='field has-addons'>" +
    "<div class='control'><div class='select is-fullwidth'><select id='artist-select'>"
    for (var i = 0; i < data.artists.length; i++) {
      var option = document.createElement("option");
      selectList = selectList + "<option value='" + 
        data.artists[i].id+ "'>" + 
        data.artists[i].name + "</option>"
    }
    selectList = selectList + "</select></div></div><div class='control'>" + 
    "<button class='button is-primary' id='artist-submit'>Select Artist" + 
    "</button></div></div>"
    form.innerHTML = selectList
    addListenersForArtist(id)
  }

  function addListenersForArtist(id) {
    artist_select = document.getElementById("artist-select")
    artist_submit = document.getElementById("artist-submit")
    artist_id = artist_select.options[0].value
    artist_select.addEventListener("change", (e) => {
      artist_id = e.target.options[e.target.options.selectedIndex].value
    })
    artist_submit.addEventListener('click', (e) => {
      e.preventDefault
      fetch(("#{ENV['API_URL']}/auto_fill?artist_id=" +
        artist_id + "&title=" + title_func(id).value))
        .then(data => data.json()).then(data => songDropdown(data, id))
    })
  }

  function songDropdown(data, id) {
    var selectSong = "<div class='field has-addons'>" +
    "<div class='control'><div class='select is-fullwidth'><select id='song-select'>"
    for (var i = 0; i < data.tracks.length; i++) {
      var option = document.createElement("option");
      selectSong = selectSong + "<option value='" +
        data.tracks[i].id+ "'>" +
        data.tracks[i].title + "</option>"
    }
    selectSong = selectSong + "</select></div></div><div class='control'>" + 
    "<button class='button is-primary' id='song-submit'>Select Song" + 
    "</button></div></div>"
    form.innerHTML += selectSong
    addEventListenersForSong(id)
  }

  function addEventListenersForSong(id) {
    song_select = document.getElementById("song-select")
    song_submit = document.getElementById("song-submit")
    song_id = song_select.options[0].value
    // title.value = song_select.options[0].text
    song_select.addEventListener("change", (e) => {
      song_id = e.target.options[e.target.options.selectedIndex].value
    })
    song_submit.addEventListener('click', (e) => {
      e.preventDefault
      title.value = song_select.options[song_select.options.selectedIndex].text
      fetch(("#{ENV['API_URL']}/auto_fill?song_id=" +
        song_id)).then(data => data.json()).then(data => fillForm(data,id))
      console.log(song_id)
    })
  }

  function fillForm(data, id) {
    console.log(data)
    year_func(id).value = data.date
    genre_func(id).value = data.genre
    album_func(id).value = data.title
    artist_func(id).value = data.artists
  }

app/views/songs/_form.slim
.card.p-4.m-3.my-5
  .columns
    .column.is-3
      - if song.image.attached?
        = image_tag(song.image)
      .field.is-grouped-centered.is-grouped
        .control
          button.button.auto-fill data-id="#{song.id}" Auto fill
      .field
        div.forming data-id="#{song.id}"
    .column
      = form_with(model: song) do |form| 
        - if song.errors.any? 
          .danger style="color: red" #{pluralize(song.errors.count, "error") } prohibited this song from being saved:
            ul
              - song.errors.each do |error| 
                li
                  = error.full_message

        .field
          .label Title
          .contol
            = form.text_field :title, class: "input name", placeholder: "Title", data: {id: "#{song.id}"}
        .field
          .label Artists
          .contol
            = form.text_field :artist, class: "input artist", placeholder: "Artist", data: {id: "#{song.id}"}
        .field
          .label Album
          .contol
            = form.text_field :album, class: "input album", placeholder: "Album", data: {id: "#{song.id}"}
        .columns
          .column
            .field 
              .label Year
              .control
                = form.text_field :year, class: "input year", placeholder: "Year", data: {id: "#{song.id}"}
          .column
            .field
              .label Genre
              .control
                = form.text_field :genre, class: "input genre", placeholder: "Genre", data: {id: "#{song.id}"}

        .field.is-grouped-centered.is-grouped
          .control
            = form.submit :Update, class: "button is-success" 

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
</div>

app/views/songs/_view.slim
.columns
  .column
    .card.p-2.m-2
      .columns
        .column.is-2
          - if song.image.attached?
            = image_tag(song.image)
        .column
          .columns
            .column
              = song.title
            .column
              = song.year
          .columns
            .column
              = song.artist
            .column
              = song.genre
        .column.is-3
          .buttons
            - if song.mp3.attached?
              = link_to "Download", update_download_path(video_id: song.video_id), class: "button"
            - else 
              / - if path == "index"
                = button_to 'Delete', song_path(song.id), method: :delete, class: "button"
              = link_to 'Retry', retry_download_path(id: song.id), class: "button"
            - if path == "user"
              = button_to 'Remove', remove_path(id: song.id), method: :post, class: "button"
            - elsif path == "index"
              = button_to 'Add', add_path(id: song.id), method: :post, class: "button"

            = link_to 'Edit', edit_song_path(song.id), class: "button"

app/views/songs/edit.slim
.is-size-1 Editing Song

= render "form", song: @song

= link_to "Back to songs", songs_path, class: "button"

= render "songs/auto_fill"

app/views/songs/index.slim
.container
  .columns
    .column
      .is-size-1 All Songs
    .column.is-4.is-flex style="align-items:center;"
      = search_form_for @q, url: songs_path do |f|
        .field.has-addons
          .control
            = f.search_field :title_or_genre_or_album_or_artist_cont, class: "input", placeholder: "Search"
          .control
            = f.submit "Search", class: "button is-info"

  - @songs.each do |song|
    - if song.updated != 0
      = render "songs/view", song: song, path: "index"
    - else 
      = render "songs/form", song: song

  = paginate @songs
= render "songs/auto_fill"

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>

app/views/songs/user_index.slim
.container
  .columns
    .column
      .is-size-1 My Songs
    .column.is-2.is-flex style="align-items:center;"
      = link_to "Download All", download_all_path, class: "button is-success"
  .columns
    .column
      = search_form_for @q, url: user_songs_path do |f|
        .field.has-addons.pb-3
          .control
            = f.search_field :title_or_genre_or_album_or_artist_cont, class: "input", placeholder: "Search"
          .control
            = f.submit "Search", class: "button is-info"
    .column
      = link_to "All", user_songs_path, class: "button"
      = link_to "Not Updated", user_not_updated_path, class: "button"
      = link_to "Updated", user_updated_path, class: "button"

  - @songs.each do |song|
    - if song.updated != 0
      = render "songs/view", song: song, path: "user"
    - else
      = render "songs/form", song: song

  = paginate @songs
= render "songs/auto_fill"

app/views/songs/user_not_updated.slim
.container
  .columns
    .column
      .is-size-1 My Songs
  .columns
    .column
      = search_form_for @q, url: user_songs_path do |f|
        .field.has-addons.pb-3
          .control
            = f.search_field :title_or_genre_or_album_or_artist_cont, class: "input", placeholder: "Search"
          .control
            = f.submit "Search", class: "button is-info"
    .column
      = link_to "All", user_songs_path, class: "button"
      = link_to "Not Updated", user_not_updated_path, class: "button"
      = link_to "Updated", user_updated_path, class: "button"

  - @songs.each do |song|
    = render "songs/form", song: song

  = paginate @songs

= render "songs/auto_fill"

app/views/songs/user_updated.slim
.container
  .columns
    .column
      .is-size-1 My Songs
    .column.is-2.is-flex style="align-items:center;"
      = link_to "Download All", download_all_path, class: "button is-success"
  .columns
    .column
      = search_form_for @q, url: user_songs_path do |f|
        .field.has-addons.pb-3
          .control
            = f.search_field :title_or_genre_or_album_or_artist_cont, class: "input", placeholder: "Search"
          .control
            = f.submit "Search", class: "button is-info"
    .column
      = link_to "All", user_songs_path, class: "button"
      = link_to "Not Updated", user_not_updated_path, class: "button"
      = link_to "Updated", user_updated_path, class: "button"

  - @songs.each do |song|
     = render "songs/view", song: song, path: "user"

  = paginate @songs