config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  resources :songs
  devise_for :users

  # Static pages
  root to: 'static_pages#home'
  get 'privacy', to: 'static_pages#privacy_policy'
  post 'contact_mail', to: 'static_pages#contact_mail'
  get 'contact', to: 'static_pages#contact'
  get 'terms', to: 'static_pages#terms_of_use'
  get 'copyright', to: 'static_pages#copyright_claims'
  get 'test', to: 'test#test'

  # Search
  get 'search', to: 'search#get'
  post 'search', to: 'search#post'

  # Playlist
  get 'user_songs', to: 'songs#user_index'
  get 'user_updated', to: 'songs#user_updated'
  get 'user_not_updated', to: 'songs#user_not_updated'
  get 'auto_fill', to: 'songs#auto_fill'
  post 'remove', to: 'playlist#remove'
  post 'add', to: 'playlist#add'
  get 'profile', to: 'profiles#show'

  # Albums
  get 'albums', to: 'albums#get'

  # Devices
  delete 'wipe_device', to: 'devices#wipe_device'
  delete 'delete_device', to: 'devices#destroy'
  post 'merge_devices', to: 'devices#merge'

  # Downloads
  get 'internal_download', to: 'download#internal'
  get 'external_download', to: 'download#external'
  get 'update_download', to: 'download#update'
  get 'download_all', to: 'download#all'
  get 'retry_download', to: 'download#retry'

  # Notifications
  get 'get_uuid', to: 'notifications#get_uuid'
  get 'mark_as_read', to: 'notifications#mark_as_read'
end

app/views/layouts/_error_messages.slim
.div#finder
  - flash.each do |k, v|
    - if k == "alert"
      = content_tag :div, class: "notification is-danger", style: "position:relative;border-radius:0px;"
        = v
        button.delete#buttonid
    - elsif k == "notice"
      = content_tag :div, class: "notification is-success", style: "position:relative;border-radius:0px;"
        = v
        button.delete#buttonid

javascript:
  
  var button = document.getElementById("buttonid");
  var notifications = document.getElementById("finder");

  button.addEventListener("click", () => {
    notifications.style.display = "none"
  })

app/views/layouts/_footer.slim
.foot
	.columns.px-5.pt-2
		.column
			a.has-text-black href="https://github.com/h4ppyr0gu3/musicApp" target="_blank" Support docs
		.column
			= link_to "Contact us", contact_path, class: "has-text-black"
		.column
			= link_to "Terms of Use", terms_path, class: "has-text-black"
		.column 
			= link_to "Privacy Policy", privacy_path, class: "has-text-black"
		.column
			= link_to "Copyright Claims", copyright_path, class: "has-text-black"
	.has-text-centered.has-text-black Disclaimer: This application is purely for educational purposes.

app/views/layouts/_header.slim
nav.navbar.m-2.p-2 aria-label=("main navigation") role="navigation" 
  .navbar-brand
    = link_to "Mapp", search_path, class: "navbar-brand has-text-dark is-size-3"
    a.navbar-burger aria-expanded="false" aria-label="menu" data-target="burger" role="button" 
      span aria-hidden="true" 
      span aria-hidden="true" 
      span aria-hidden="true" 
        - if @notifications_count >= 1
          span.has-background-danger style='position: absolute; top: -10px; right: -10px; \
          border-radius: 0.5rem; max-height: 20px; font-size: 0.8rem; padding: 3px; \
          padding-top: 0px; z-index: 20;' #{@notifications_count}
  .navbar-menu#burger
    .navbar-start
      = link_to "All Songs", songs_path, class: "navbar-item has-text-dark"
      = link_to "Search", search_path, class: "navbar-item has-text-dark"
      = link_to "Album Request", albums_path, class: "navbar-item has-text-dark"
      - if user_signed_in?
        = link_to "My Songs", user_songs_path, class: "navbar-item has-text-dark"
    .navbar-end
      .navbar-item
        .buttons
          - if user_signed_in?
            .dropdown.mx-3#drop-trigger
              .dropdown-trigger
                - if @notifications_count > 1
                  span.has-background-danger style='position: absolute; top: -10px; right: -10px; \
                  border-radius: 0.5rem; max-height: 20px; font-size: 0.8rem; padding: 3px; \
                  padding-top: 0px; z-index: 20;' #{@notifications_count}
                button.button aria-haspopup="true" aria-controls="dropdown-menu"
                  span Notifications
              .dropdown-menu#dropdown-menu role="menu" style="max-height: 20rem; overflow: auto;"
                .dropdown-content.p-2
                  .dropdown-item.button#mark-read Mark all as read
                  - @notifications.each do |notification|
                    a.dropdown-item style="white-space: normal !important;"
                      = notification.text.html_safe
            = link_to "Profile", profile_path, class: "button is-link"
            = button_to "Log Out", destroy_user_session_path, method: :delete, class: "button"
          - else
            = link_to "Sign Up", new_user_registration_path, class: "button is-primary"
            = link_to "Sign In", new_user_session_path, class: "button"

= render "layouts/error_messages"

javascript:

  document.addEventListener('DOMContentLoaded', () => {
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
    if ($navbarBurgers.length > 0) {
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {
          const target = el.dataset.target;
          const $target = document.getElementById(target);
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');
        });
      });
    }
    var drop_trigger = document.getElementById("drop-trigger");
    drop_trigger.addEventListener('click', (e) => {
      drop_trigger.classList.toggle('is-active');
    });
    var mark_read = document.getElementById("mark-read");
    mark_read.addEventListener('click', (e) => {
      e.preventDefault();
      fetch("#{ENV['API_URL']}/mark_as_read")
    });
  });

app/views/layouts/_search_js.slim
javascript:

  download = document.getElementsByClassName("download")
  for( i = 0; i < download.length; i++) {
    download[i].addEventListener("click", (e) => {
      fetch(("#{ENV['API_URL']}/external_download?video_id=" + 
      encodeURIComponent(e.target.dataset.video) + 
      "&user_id=" +  encodeURIComponent(e.target.dataset.user) +
      "&channel=" + encodeURIComponent(e.target.dataset.channel) +
      "&title=" + encodeURIComponent(e.target.dataset.title) +
      "&image_url=" + encodeURIComponent(e.target.dataset.image)))

      e.target.classList.add("is-success");
    })
  }

  play = document.getElementsByClassName("play");
  video_field = document.getElementsByClassName("video");
  for ( i = 0; i < play.length; i++ ) {
    play[i].addEventListener("click", (e) => {
    toggle_video(e.target.dataset.id)}
    , false);
  };

  function toggle_video(id) {
    for ( i = 0; i < video_field.length; i++) {
      if (video_field[i].dataset.id == id) {
        if (video_field[i].innerHTML == "") {
          video_field[i].innerHTML = "<iframe width='560' height='315' src='"
          + video_field[i].dataset.url
          + "' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; encrypted-media;' allowfullscreen</iframe>"
        } else {
          video_field[i].innerHTML = "";
        }
      }
    }
  };

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%# <link rel="stylesheet" href="custom.css"> %>
<style>
#notification-dropdown {
  max-height: 10rem;
  overflow: auto;
  position: absolute;
  min-width: 10rem;
  max-width: 30rem;
  z-index: 3;
  background: #f9f9f9;
  border-radius: 0.5rem;
}

.notification-element {
  padding: 5px;
  margin: 5px;
  border-top: 2px solid #c7c9c7;
}
</style>
<!-- <%# <%= stylesheet_link_tag 'custom.css' %> %> -->
<!-- <%# <%= favicon_link_tag 'fav.ico' %> %> -->
  <link rel="icon" type="image/x-icon" href="/favicon.ico">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>